export const githubProfileData = {
    "login": "VTU9730",
    "id": 104155228,
    "node_id": "U_kgDOBjVIXA",
    "avatar_url": "https://avatars.githubusercontent.com/u/104155228?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/VTU9730",
    "html_url": "https://github.com/VTU9730",
    "followers_url": "https://api.github.com/users/VTU9730/followers",
    "following_url": "https://api.github.com/users/VTU9730/following{/other_user}",
    "gists_url": "https://api.github.com/users/VTU9730/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/VTU9730/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/VTU9730/subscriptions",
    "organizations_url": "https://api.github.com/users/VTU9730/orgs",
    "repos_url": "https://api.github.com/users/VTU9730/repos",
    "events_url": "https://api.github.com/users/VTU9730/events{/privacy}",
    "received_events_url": "https://api.github.com/users/VTU9730/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "name": "Siddavatam Veeraprathap Reddy",
    "company": "Infosys",
    "blog": "",
    "location": "Hyderabad",
    "email": null,
    "hireable": true,
    "bio": "Crazy on programming at the moment",
    "twitter_username": null,
    "public_repos": 46,
    "public_gists": 0,
    "followers": 0,
    "following": 3,
    "created_at": "2022-04-21T15:25:33Z",
    "updated_at": "2024-11-23T13:34:30Z"
    }